name: Pipeline Control Security

on: [push]

jobs:
  build:
    name: Build and initialize DB
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          MYSQL_DATABASE: onlinebookstore
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Configura JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache dipendenze Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Attendi MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h127.0.0.1 -uroot -p${{ secrets.TEST_DB_PASSWORD }} --silent; then
              echo "MySQL pronto!"
              break
            fi
            echo "Attendo MySQL..."
            sleep 2
          done

      - name: Inizializza database
        run: |
          mysql -h127.0.0.1 -uroot -p${{ secrets.TEST_DB_PASSWORD }} <<EOF
          USE onlinebookstore;
          CREATE TABLE IF NOT EXISTS books(
            barcode VARCHAR(100) PRIMARY KEY,
            name VARCHAR(100),
            author VARCHAR(100),
            price INT,
            quantity INT
          );
          CREATE TABLE IF NOT EXISTS users(
            username VARCHAR(100) PRIMARY KEY,
            password VARCHAR(100),
            firstname VARCHAR(100),
            lastname VARCHAR(100),
            address TEXT,
            phone VARCHAR(100),
            mailid VARCHAR(100),
            usertype INT
          );
          INSERT INTO books VALUES
            ('9781491950296', 'Clean Architecture', 'Robert C. Martin', 380, 10),
            ('9780596007126', 'Head First Design Patterns', 'Eric Freeman & Elisabeth Freeman', 420, 6);

          INSERT INTO users VALUES
            ('mario', 'mypass', 'Mario', 'Rossi', 'Milano', '3341122334', 'mario.rossi@email.com', 1),
            ('lucia', 'secret123', 'Lucia', 'Bianchi', 'Roma', '3399988776', 'lucia.bianchi@email.com', 2);

          COMMIT;
          EOF

      - name: Build progetto (Maven)
        run: mvn clean install -B

      - name: Upload unverified artifact
        uses: actions/upload-artifact@v4
        with:
          name: unverified-java-build-artifact
          path: |
            target/
            pom.xml

  sast:
    name: Analisi statica (SonarQube)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configura JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Esegui SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=MactarSck_SistemiSicurezza

  sca:
    name: Analisi dipendenze (Dependency Check)
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Configura JDK 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build senza test
        run: mvn -B package -DskipTests

      - name: Esegui Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: onlinebookstore
          path: '.'
          format: HTML
          out: reports
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Carica report Dependency Check
        uses: actions/upload-artifact@v4
        with:
          name: Report-Dependency-Check
          path: reports

  package:
    name: Caricamento artefatto finale
    runs-on: ubuntu-latest
    needs: [sast, sca]

    steps:
      - name: Scarica artefatto buildato
        uses: actions/download-artifact@v4
        with:
          name: unverified-java-build-artifact
          path: .

      - name: Carica artefatto WAR
        uses: actions/upload-artifact@v4
        with:
          name: artefatto-app
          path: target/*.war
